name: build
run-name: deploy-to-website
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g elm
      - run: elm make src/Minesweeper.elm --output build.js
